name: kapowarr-dev

services:
  kapowarr:
    build:
      context: .
    image: kapowarr-local:latest
    container_name: kapowarr
    restart: unless-stopped
    environment:
      PUID: "1000"
      PGID: "1000"
      TZ: Europe/London
    volumes:
      - /volume3/docker/personal/appdata/kapowarr:/app/db
      - /volume2/downloads/complete/comics/completed:/app/temp_downloads/completed
      - /volume1/media/Comics:/comics
    ports:
      - "5656:5656"
    labels:
      com.centurylinklabs.watchtower.enable: "false"
